src/Entity/File.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FileRepository")
 */
class File implements \Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_creation;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_last_modification;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=0, nullable=true)
     */
    private $size;

    /**
     * @ORM\Column(type="blob")
     */
    private $data;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $tags;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Folder", inversedBy="files")
     * @ORM\JoinColumn(nullable=false)
     */
    private $folder;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="files")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\DocType", inversedBy="files")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type;

    public function __construct()
    {
        $this->date_creation = new \DateTime();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getDateLastModification(): ?\DateTimeInterface
    {
        return $this->date_last_modification;
    }

    public function setDateLastModification(?\DateTimeInterface $date_last_modification): self
    {
        $this->date_last_modification = $date_last_modification;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSize()
    {
        return $this->size;
    }

    public function setSize($size): self
    {
        $this->size = $size;

        return $this;
    }

    public function getData()
    {
        return $this->data;
    }

    public function setData($data): self
    {
        $this->data = $data;

        return $this;
    }

    public function getTags(): ?string
    {
        return $this->tags;
    }

    public function setTags(?string $tags): self
    {
        $this->tags = $tags;

        return $this;
    }

    public function getFolder(): ?Folder
    {
        return $this->folder;
    }

    public function setFolder(?Folder $folder): self
    {
        $this->folder = $folder;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getType(): ?DocType
    {
        return $this->type;
    }

    public function setType(?DocType $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * String representation of object
     * @link http://php.net/manual/en/serializable.serialize.php
     * @return string the string representation of the object or null
     * @since 5.1.0
     */
    public function serialize()  : string
    {
        return serialize([$this->id,$this->folder,$this->author,$this->data,$this->date_creation,$this->date_last_modification,$this->description,$this->name,$this->size,$this->tags,$this->type]);
    }

    /**
     * Constructs the object
     * @link http://php.net/manual/en/serializable.unserialize.php
     * @param string $serialized <p>
     * The string representation of the object.
     * </p>
     * @return void
     * @since 5.1.0
     */
    public function unserialize($serialized) : void
    {
        [$this->id,$this->folder,$this->author,$this->data,$this->date_creation,$this->date_last_modification,$this->description,$this->name,$this->size,$this->tags,$this->type] = unserialize($serialized, ['allowed_classes' => false]);
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface, \Serializable
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $user_first_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $user_last_name;

    /**
     * @var array
     *
     * @ORM\Column(type="json")
     */
    private $roles = [];


    /**
     * @var boolean
     *
     * @ORM\Column(type="boolean")
     */
    private $user_deleted;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\File", mappedBy="author", orphanRemoval=true)
     */
    private $files;

    public function __construct()
    {
        $this->files = new ArrayCollection();
    }

    /**
     * @return boolean
     */
    public function getUserDeleted()
    {
        return $this->user_deleted;
    }

    /**
     * @param array $user_deleted
     */
    public function setUserDeleted($user_deleted): void
    {
        $this->user_deleted = $user_deleted;
    }

    /**
     * @return integer
     */
    public function getId() : int
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getUserFirstName()
    {
        return $this->user_first_name;
    }

    /**
     * @param mixed $user_first_name
     */
    public function setUserFirstName($user_first_name): void
    {
        $this->user_first_name = $user_first_name;
    }

    /**
     * @return mixed
     */
    public function getUserLastName()
    {
        return $this->user_last_name;
    }

    /**
     * @param mixed $user_last_name
     */
    public function setUserLastName($user_last_name): void
    {
        $this->user_last_name = $user_last_name;
    }


    /**
     * @return array
     */
    public function getRoles(): array
    {
        $roles = $this->roles;

        // Afin d'être sûr qu'un user a toujours au moins 1 rôle
        if (empty($roles)) {
            $roles[] = 'ROLE_USER';
        }

        return array_unique($roles);
    }

    /**
     * @param array $roles
     */
    public function setRoles(array $roles): void
    {
        $this->roles = $roles;
    }

    /**
     * Returns the password used to authenticate the user.
     *
     * This should be the encoded password. On authentication, a plain-text
     * password will be salted, encoded, and then compared to this value.
     *
     * @return string The password
     */
    public function getPassword() : ?string
    {
        return $this->password;
    }

    /**
     * @param $password
     */
    public function setPassword(string $password) : void
    {
        $this->password=$password;
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt() : ?string
    {
        return null;
    }

    /**
     * Returns the username used to authenticate the user.
     *
     * @return string The username
     */
    public function getUsername() : ?string
    {
        return $this->username;
    }

    public function setUsername(string $user_login) : void
    {
        $this->username = $user_login;
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials() : void
    {
        //unused
    }

    /**
     * String representation of object
     * @link http://php.net/manual/en/serializable.serialize.php
     * @return string the string representation of the object or null
     * @since 5.1.0
     */
    public function serialize()  : string
    {
        return serialize([$this->id, $this->username, $this->password]);
    }

    /**
     * Constructs the object
     * @link http://php.net/manual/en/serializable.unserialize.php
     * @param string $serialized <p>
     * The string representation of the object.
     * </p>
     * @return void
     * @since 5.1.0
     */
    public function unserialize($serialized) : void
    {
        [$this->id, $this->username, $this->password] = unserialize($serialized, ['allowed_classes' => false]);
    }

    /**
     * @return Collection|File[]
     */
    public function getFiles(): Collection
    {
        return $this->files;
    }

    public function addFile(File $file): self
    {
        if (!$this->files->contains($file)) {
            $this->files[] = $file;
            $file->setAuthor($this);
        }

        return $this;
    }

    public function removeFile(File $file): self
    {
        if ($this->files->contains($file)) {
            $this->files->removeElement($file);
            // set the owning side to null (unless already changed)
            if ($file->getAuthor() === $this) {
                $file->setAuthor(null);
            }
        }

        return $this;
    }
}

templates/pages/doc-details.html.twig
<!DOCTYPE html>
<html>
<head>
    <link href="https://bootswatch.com/4/flatly/bootstrap.min.css" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>
<body>

<div class="body docdetails">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    
        <span class="navbar-brand" href="#">{{ doc.name }}</span>

        <div class="float-right">
            <a class="btn btn-success " href="{{ path('doc_show', {'id': doc.id}) }}" data-toggle="tooltip" title="Prévisualiser" >
                {% if doc.type.typename == 'image' %}
                    <i class="fa fa-file-image-o" aria-hidden="true"></i>
                {%  else %}
                    <i class="fa fa-file-pdf-o" aria-hidden="true"></i>
                {% endif %}
            </a>

            <a class="btn btn-info " href="{{ path('doc_show', {'id': doc.id}) }}" target="_blank" data-toggle="tooltip" title="Nouvel onglet">
                <i class="fa fa-external-link" aria-hidden="true"></i>
            </a>

        </div>
    </nav>
    <div class="ml-2 doc-infos">
        <p><b>Auteur :</b> {{ doc.author.username }}<br/>
            <b>Description :</b> {{ doc.description}}<br/>
            <b>Type :</b> {{ doc.type.typeName }}<br/>
            <b>Date de création :</b> {{ doc.dateCreation|date('d/m/Y')}}<br/>
            <b>Dernière modification le :</b> {{ doc.dateLastModification|date('d/m/Y')}}<br/>
            <b>Taille :</b> {{ doc.size }}<br/>
            <b>Tags :</b> {{ doc.tags }}</p>

    </div>
</div>

</body>
</html>

templates/pages/form.html.twig
{{ form(form) }}

templates/pages/home.html.twig
{% extends 'includes/base-template.html.twig' %} {% block body %}

<nav aria-label="breadcrumb">
	<ol class="breadcrumb path-banner row">
		<div class="d-flex align-items-center col-md-8">
			<li class="breadcrumb-item" aria-current="page"><a href="{{ path('home') ~ '?folderID=1'}}">Racine</a></li>
            {% for folder in parents %}
                {% if folder.getId == root_folder.getId %}
					<li class="breadcrumb-item active" aria-current="page">
						<a class="align-self-center" href="{{ path('home') ~ '?folderID=' ~ folder.id}}">{{ folder.name }}</a>
					</li>
                {% else %}
					<li class="breadcrumb-item" aria-current="page">
						<a href="{{ path('home') ~ '?folderID=' ~ folder.id}}">{{ folder.name }}</a>
					</li>
                {% endif %}
            {% endfor %}
		</div>
		<div class="buttons-files col-md-4">

		<button type="button" class="btn btn-primary button-file float-right"
			data-toggle="modal" data-target="#ajoutFichier">Ajouter un
			Fichier</button>

		<!-- Modal -->
		<div class="modal fade" id="ajoutFichier" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
		  <div class="modal-dialog" role="document">
			<div class="modal-content">
			  <div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">Ajouter un fichier</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				  <span aria-hidden="true">&times;</span>
				</button>
			  </div>
				<form action="{{ path('doc_create', {'folderID' : root_folder.getId}) }}" method="post" enctype="multipart/form-data">
				  <div class="modal-body">

					<!-- TAGS -->
					  <div class="form-group">
						  <label for="doc_form_tags" class="required col-form-label">Tags</label>
						  <input id="doc_form_tags" name="doc_form[tags]" required="required" type="text" placeholder="Tag, Tag, Tag, Tag ..." class="form-control">
					  </div>

					<!-- Description -->
					  <div class="form-group">
						  <label for="doc_form_description" class="required">Description</label>
						  <input id="doc_form_description" name="doc_form[description]" required="required" type="text" class="form-control">
					  </div>

					<!-- import -->
					  <div class="form-group">
						  <label for="doc_form_data" class="required">Fichier</label>
						  <input id="doc_form_data" name="doc_form[data]" required="required" type="file" class="form-control-file" aria-describedby="fileHelp">
					  </div>
					  <input id="doc_form_token" name="doc_form[_token]" value="{{ csrf_token('file') }}" type="hidden">
				  </div>
				  <div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
					<button class="btn btn-primary" type="submit">Ajouter</button>
				  </div>
				</form>
			</div>
		  </div>
		</div>
	
		<button type="button" class="btn btn-primary float-right button-file" data-toggle="modal" data-target="#ajoutDossier">
		  Ajouter un Dossier
		</button>

		<!-- Modal -->
		<div class="modal fade" id="ajoutDossier" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
		  <div class="modal-dialog" role="document">
			<div class="modal-content">
			  <div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">Ajouter un dossier</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				  <span aria-hidden="true">&times;</span>
				</button>
			  </div>

				<form action="{{ path('folder_create', {'folderID' : root_folder.getId}) }}" method="post">
				  <div class="modal-body">
					<!-- Nom -->
					<div class="form-group">
					  <label class="col-form-label required" for="folder_form_name">Nom du dossier</label>
					  <input class="form-control" placeholder="Nom du dossier" id="folder_form_name" name="folder_form[name]" required="required" type="text">
					</div>

				  </div>
					<input id="folder_form_token" name="folder_form[_token]" value="{{ csrf_token('folder') }}" type="hidden">
				  <div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
					<button class="btn btn-primary" type="submit">Ajouter</button>
				  </div>
				</form>
			</div>
		  </div>
		</div>
		</div>
	</ol>

</nav>

<div class="row">
	<div class="col-md-8 no-margin">
		<div class="files-tab ml-1">
			<table class="table table-striped">
				<thead>
					<tr>
						<th scope="col"></th>
						<th scope="col">Nom</th>
						<th scope="col">Date de création</th>
						<th scope="col">Type</th>
						<th scope="col">Taille</th>
						<th scope="col">Tags</th>
						<th scope="col">Créateur</th>
						<th scope="col">Supprimer</th>
					</tr>
				</thead>

				<tbody>
					<tr>
						<th scope="row"></th>
						<td><a
							href="{{ path('home') ~ '?folderID=' ~ root_folder.parent.id }}">../</a></td>
						<td></td>
						<td>folder</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					{% for folder in listFolder if folder.getId != 1 %}
					<tr>
						<th scope="row"></th>
						<td><a href="{{ path('home') ~ '?folderID=' ~ folder.id}}">{{folder.name
								}}/</a></td>
						<td></td>
						<td>folder</td>
						<td></td>
						<td></td>
						<td></td>
						<td><a href="{{path('folder_delete',  {'id' : folder.id, 'folderID' : root_folder.getId}) }}"><button
									class="btn btn-muted">
									<i class="fa fa-trash" aria-hidden="true"></i>
								</button></a></td>
					</tr>
					{% endfor %} {% for file in listFile %}
					<tr>
						<th scope="row"></th>
						<td><span class="file-clickable"
							value="{{ path('doc_details',  {'id' : file.id}) }}">{{file.name
								}}</span></td>
						<td>{{ file.dateCreation|date('d/m/Y')}}</td>
						<td>{{ file.type.typeName }}</td>
						<td>{{ file.size }} octets</td>
						<td>{{ file.tags }}</td>
						<td>{{ file.author.username }}</td>
						<td><a href="{{path('doc_delete',  {'id' : file.id, 'folderID' : root_folder.getId}) }}">
								<button class="btn btn-muted">
									<i class="fa fa-trash" aria-hidden="true"></i>
								</button>
						</a></td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>

	<div class="col-md-4 docdetails-panel">
		<iframe src="" class="iframe-docdetails" seamless> </iframe>
	</div>
</div>

{% block javascripts %}
<script>
	            $(".file-clickable").click( function() {
	                $(".iframe-docdetails").attr("src", this.getAttribute("value"));
	            })
	        </script>
{% endblock %} {% endblock %}

templates/pages/login.html.twig
{% extends 'includes/base-template.html.twig' %}

{% block body %}
    <div class="col-lg-4 mx-auto jumbotron form ">
        <form action="{{ path('security_login') }}" method="post">

            <h3 class="form-signin-heading">Se connecter</h3>

            {% if error %}
                <div class="alert alert-dismissible alert-danger">Nom d'utilisateur ou mot de passe incorrect.</div>
            {% endif %}
            <div class="form-group">
                <label for="username">Nom d'utilisateur</label>
                <input type="text" id="username" name="_username" required="required" placeholder="Nom d'utilisateur" class="form-control"/>
            </div>

            <div class="form-group">
                <label for="password">Mot de passe</label>
                <input type="password" id="password" name="_password" required="required" placeholder="Mot de passe" class="form-control"/>
            </div>

            <label class="checkbox">
                <input type="checkbox" value="remember-me" id="rememberMe" name="rememberMe"> Se souvenir de moi
            </label>
            <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}"/>

            <button class="btn btn-lg btn-primary btn-block" type="submit">Connexion</button>
            <a href="{{ path('user_registration') }}">
                <button class="btn btn-lg btn-success register mx-auto col-lg-12 mt-2">S'enregistrer</button>
            </a>
        </form>
    </div>
{% endblock %}

templates/pages/nav-example.html.twig
{% extends 'twig/includes/base-template.html.twig' %}

{% block header %}
{% endblock %}

{% block footer %}
{% endblock %}

templates/pages/register.html.twig
{% extends 'includes/base-template.html.twig' %}

{% block body %}
<div class="col-lg-4 mx-auto jumbotron form">
    <form name="user" method="post">
        <h3>S'inscrire</h3>
        <hr>
        {% if form_errors(form) %}
            <div class="alert alert-dismissible alert-danger">{{ form_errors(form) }}</div>
        {% endif %}

        <div class="form-group {% if form_errors(form.user_first_name) %}has-danger{% endif %}">
            <label for="user_first_name">Nom</label>
            <input type="text" id="user_first_name" name="user[user_first_name]" required="required" placeholder="Nom" class="form-control {% if form_errors(form.user_first_name) %}is-invalid{% endif %}"/>
            <div class="invalid-feedback">Ce champs est invalide.</div>
        </div>

        <div class="form-group {% if form_errors(form.user_last_name) %}has-danger{% endif %}">
            <label for="user_last_name">Prénom</label>
            <input type="text" id="user_last_name" name="user[user_last_name]" required="required" placeholder="Prénom" class="form-control {% if form_errors(form.user_last_name) %}is-invalid{% endif %}"/>
            <div class="invalid-feedback">Ce champs est invalide.</div>
        </div>

        <div class="form-group {% if form_errors(form.username) %}has-danger{% endif %}">
            <label for="user_username">Nom d'utilisateur</label>
            <input type="text" id="user_username" name="user[username]" required="required" placeholder="Nom d'utilisateur" class="form-control {% if form_errors(form.password.first) %}is-invalid{% endif %}"/>
            <div class="invalid-feedback">Ce champs est invalide.</div>
        </div>


        <div class="form-group {% if form_errors(form.password.first) %}has-danger{% endif %}">
            <label for="user_password_first">Mot de passe</label>
            <input type="password" id="user_password_first" name="user[password][first]" required="required" placeholder="Mot de passe" class="form-control {% if form_errors(form.password.first) %}is-invalid{% endif %}"/>
            <div class="invalid-feedback">Ce champs est invalide.</div>
        </div>


        <div class="form-group {% if form_errors(form.password.second) %}has-danger{% endif %}">
            <label for="user_password_second">Répéter le mot de passe</label>
            <input type="password" id="user_password_second" name="user[password][second]" required="required" placeholder="Répéter mot de passe" class="form-control {% if form_errors(form.password.first) %}is-invalid{% endif %}"/>
            <div class="invalid-feedback">Ce champs est invalide.</div>
        </div>

        {{ form_row(form._token) }}

        <button type="submit" class="btn btn-primary col-md-12">S'inscrire</button>
        <a href="{{ path('security_login') }}"><button class="btn btn-success col-md-12 mt-2">Se connecter</button></a>
    </form>
</div>

{% endblock %}

templates/pages/search.html.twig
{% extends 'includes/base-template.html.twig' %} {% block body %}
<nav aria-label="breadcrumb">

	<ol class="breadcrumb">
		<li aria-current="page">Recherche : &nbsp;</li>
		<li aria-current="page">{{listWord}}</li>
	</ol>
</nav>
<div class="row">
	<div class="col-md-8 no-margin">
		<div class="files-tab ml-1">
			<table class="table table-striped">
				<thead>
					<tr>
						<th scope="col"></th>
						<th scope="col">Nom</th>
						<th scope="col">Date création</th>
						<th scope="col">Type</th>
						<th scope="col">Taille</th>
                        <th scope="col">Tags</th>
						<th scope="col">Créateur</th>
						<th scope="col">Supprimer</th>
					</tr>
				</thead>

                    <tbody>
                    {% for file in listFile %}
                        <tr>
                            <th scope="row"> </th>
                            <td><span class="file-clickable" value="{{ path('doc_details',  {'id' : file.id}) }}">{{ file.name }}</span></td>
                            <td>{{ file.dateCreation|date('d/m/Y')}}</td>
                            <td>{{ file.type.typeName }} </td>
                            <td>{{ file.size }} octets</td>
                            <td>{{ file.tags }}</td>
                            <td>{{ file.author.username }} </td>
                            <td><a href="{{path('doc_delete',  {'id' : file.id}) }}">
                                    <button class="btn btn-muted"><i class="fa fa-trash" aria-hidden="true"></i></button>
                                </a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    <div class="col-md-4 docdetails-panel">
        <iframe src="" class="iframe-docdetails" seamless> </iframe>
    </div>
</div>

{% block javascripts %}
<script src="{{ asset('js/print-js/dist/print.js') }}"></script>
<script>
            $(".file-clickable").click( function() {
                $(".iframe-docdetails").attr("src", this.getAttribute("value"));
            })
        </script>

{% endblock %} 
{% endblock %}

templates/pages/stats.html.twig
{% extends 'includes/base-template.html.twig' %}

{% block body %}
    <div>
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col">Taille totale</th>
                {% for name in names %}
                <th scope="col">{{ name }}</th>
                {% endfor %}
            </tr>
            </thead>

            <tbody>
                <tr>
                    <th scope="row"> </th>
                    <td>{{ sizeTotal }} octets</td>
                    {% for value in values %}
                        <td scope="col">{{ value }}</td>
                    {% endfor %}
                </tr>
            </tbody>
        </table>
    </div>


{% endblock %}

templates/pages/user-details.html.twig
{% extends 'includes/base-template.html.twig' %}
{% block body %}


<div class="body userdetails">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <span class="navbar-brand" href="#">Fiche utilisateur</span>
    </nav>
    <div class="ml-2 doc-infos" align="center">
        <p><b>Utilisateur :</b> {{ user.username }}<br/>
            <b>Nom :</b> {{ user.userFirstName}}<br/>
            <b>Prénom :</b> {{ user.userLastName }}<br/>
            <b>Droits: </b> 
            	{% for role in user.roles %}
            		{{role}}
            	{% endfor %}
            </br>

    </div>
</div>

{% endblock %}