src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface, \Serializable
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $user_first_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $user_last_name;

    /**
     * @var array
     *
     * @ORM\Column(type="json")
     */
    private $roles = [];


    /**
     * @var boolean
     *
     * @ORM\Column(type="boolean")
     */
    private $user_deleted;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\File", mappedBy="author", orphanRemoval=true)
     */
    private $files;

    public function __construct()
    {
        $this->files = new ArrayCollection();
    }

    /**
     * @return boolean
     */
    public function getUserDeleted()
    {
        return $this->user_deleted;
    }

    /**
     * @param array $user_deleted
     */
    public function setUserDeleted($user_deleted): void
    {
        $this->user_deleted = $user_deleted;
    }

    /**
     * @return integer
     */
    public function getId() : int
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getUserFirstName()
    {
        return $this->user_first_name;
    }

    /**
     * @param mixed $user_first_name
     */
    public function setUserFirstName($user_first_name): void
    {
        $this->user_first_name = $user_first_name;
    }

    /**
     * @return mixed
     */
    public function getUserLastName()
    {
        return $this->user_last_name;
    }

    /**
     * @param mixed $user_last_name
     */
    public function setUserLastName($user_last_name): void
    {
        $this->user_last_name = $user_last_name;
    }


    /**
     * @return array
     */
    public function getRoles(): array
    {
        $roles = $this->roles;

        // Afin d'être sûr qu'un user a toujours au moins 1 rôle
        if (empty($roles)) {
            $roles[] = 'ROLE_USER';
        }

        return array_unique($roles);
    }

    /**
     * @param array $roles
     */
    public function setRoles(array $roles): void
    {
        $this->roles = $roles;
    }

    /**
     * Returns the password used to authenticate the user.
     *
     * This should be the encoded password. On authentication, a plain-text
     * password will be salted, encoded, and then compared to this value.
     *
     * @return string The password
     */
    public function getPassword() : ?string
    {
        return $this->password;
    }

    /**
     * @param $password
     */
    public function setPassword(string $password) : void
    {
        $this->password=$password;
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt() : ?string
    {
        return null;
    }

    /**
     * Returns the username used to authenticate the user.
     *
     * @return string The username
     */
    public function getUsername() : ?string
    {
        return $this->username;
    }

    public function setUsername(string $user_login) : void
    {
        $this->username = $user_login;
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials() : void
    {
        //unused
    }

    /**
     * String representation of object
     * @link http://php.net/manual/en/serializable.serialize.php
     * @return string the string representation of the object or null
     * @since 5.1.0
     */
    public function serialize()  : string
    {
        return serialize([$this->id, $this->username, $this->password]);
    }

    /**
     * Constructs the object
     * @link http://php.net/manual/en/serializable.unserialize.php
     * @param string $serialized <p>
     * The string representation of the object.
     * </p>
     * @return void
     * @since 5.1.0
     */
    public function unserialize($serialized) : void
    {
        [$this->id, $this->username, $this->password] = unserialize($serialized, ['allowed_classes' => false]);
    }

    /**
     * @return Collection|File[]
     */
    public function getFiles(): Collection
    {
        return $this->files;
    }

    public function addFile(File $file): self
    {
        if (!$this->files->contains($file)) {
            $this->files[] = $file;
            $file->setAuthor($this);
        }

        return $this;
    }

    public function removeFile(File $file): self
    {
        if ($this->files->contains($file)) {
            $this->files->removeElement($file);
            // set the owning side to null (unless already changed)
            if ($file->getAuthor() === $this) {
                $file->setAuthor(null);
            }
        }

        return $this;
    }
}

src/Form/UserType.php
<?php
/**
 * Created by PhpStorm.
 * User: Amaury
 * Date: 09/07/2018
 * Time: 16:41
 */

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('user_first_name',TextType::class)
            ->add('user_last_name',TextType::class)
            ->add('username', TextType::class)
            ->add('password', RepeatedType::class, array(
                'type' => PasswordType::class,
                'first_options'  => array('label' => 'Password'),
                'second_options' => array('label' => 'Repeat Password'),
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => User::class,
        ));
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;


/**
 * @Route("/admin/user")
 */
class UserController extends Controller
{
    /**
     * @Route("/", name="user_index", methods="GET")
     */
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
            'title'=>"Gestion Utilisateur",
            'connected'=>true
        ]);
    }

    /**
     * @Route("/new", name="user_new", methods="GET|POST")
     */
    public function new(Request $request,UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() ) {

            $user->setUserFirstName($form->getData()->getUserFirstName());
            $user->setUserLastName($form->getData()->getUserLastName());
            $user->setUsername($form->getData()->getUsername());
            $password = $passwordEncoder->encodePassword($user, $user->getPassword());
            $user->setPassword($password);

            // Par defaut l'utilisateur aura toujours le rôle ROLE_USER
            $user->setRoles(['ROLE_USER']);

            // l'utilisateur n'est pas supprimé
            $user->setUserDeleted(false);

            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();

            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
            'title'=>"Création Utilisateur",
            'connected'=>true
        ]);
    }

    /**
     * @Route("/{user_id}", name="user_show", methods="GET")
     */
    public function show(int $user_id): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $this->getDoctrine()->getRepository('App:User')->find($user_id),
            'title'=>"Visualisation Utilisateur",
            'connected'=>true
        ]);
    }

    /**
     * @Route("/{user_id}/edit", name="user_edit", methods="GET|POST")
     */
    public function edit(Request $request,int $user_id,UserPasswordEncoderInterface $passwordEncoder ): Response
    {
        $user = $this->getDoctrine()->getRepository('App:User')->find($user_id);
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() ) {

            $user->setUserFirstName($form->getData()->getUserFirstName());
            $user->setUserLastName($form->getData()->getUserLastName());
            $user->setUsername($form->getData()->getUsername());
            $password = $passwordEncoder->encodePassword($user, $user->getPassword());
            $user->setPassword($password);

            // Par defaut l'utilisateur aura toujours le rôle ROLE_USER
            $user->setRoles(['ROLE_USER']);

            // l'utilisateur n'est pas supprimé
            $user->setUserDeleted(false);

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_edit', ['user_id' => $user->getId()]);
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
            'title'=>"Edition Utilisateur",
            'connected'=>true
        ]);
    }

    /**
     * @Route("/user/{user_id}", name="user_delete", methods="DELETE")
     * @param Request $request
     * @param int $user_id
     * @return Response
     */
    public function delete(Request $request, int $user_id): Response
    {
        $user= $this->getDoctrine()->getRepository('App:User')->find($user_id);
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $user->setUserDeleted(true);
            $em->persist($user);
            $em->flush();
        }

        return $this->redirectToRoute('user_index');
    }

    /**
     * @return Response
     */
    public function details(): Response
    {
        return $this->render("pages/user-details.html.twig",array(
            'title'=>"Détails d'utilisateur",
            'connected'=>true,
            'user'=>$this->getUser()
        ));
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'user_id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/_form.html.twig
<form name="user" method="post" class="form-horizontal text-center">

    <div class="form-group">
        <label for="user_user_first_name" class="required control-label col-sm-2">User first name</label>
        <input id="user_user_first_name"  name="user[user_first_name]" required="required" value="{{ user.getUserFirstName }}" type="text">
    </div>
    <div class="form-group">
        <label for="user_user_last_name" class="required control-label col-sm-2">User last name</label>
        <input id="user_user_last_name" name="user[user_last_name]" required="required" value="{{ user.getUserLastName }}" type="text">
    </div>
    <div class="form-group">
        <label for="user_username" class="required control-label col-sm-2">Username</label>
        <input id="user_username" name="user[username]" required="required" value="{{ user.getUsername }}" type="text">
    </div>
    <div class="form-group">
        <label for="user_password_first" class="required control-label col-sm-2">Password</label>
        <input id="user_password_first" name="user[password][first]" required="required" type="password">
    </div>
    <div class="form-group">
        <label for="user_password_second" class="required control-label col-sm-2">Repeat Password</label>
        <input id="user_password_second" name="user[password][second]" required="required" type="password">
    </div>

    <button class="btn" type="submit">{{ button_label|default('Save') }}</button>
</form>

templates/user/edit.html.twig
{% extends 'includes/base-template.html.twig' %}

{% block body %}
    <h1 class="text-center">Edit User</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}
	<div class="text-center">
	<br>
    {{ include('user/_delete_form.html.twig') }}
    <br>
    
    <a class="btn btn-secondary" href="{{ path('user_index') }}">back to list</a>
    </div>
{% endblock %}

templates/user/index.html.twig
{% extends 'includes/base-template.html.twig' %}

{% block body %}
<div class="d-flex">
	<div class="mr-auto p-2">
    	<h1>User index</h1>
    </div>
    <div class="p-2">
    	<a type="button" class="btn btn-secondary" href="{{ path('user_new') }}">Ajouter un utilisateur</a>
    </div>
</div>

    <table class="table">
        <thead>
            <tr>
                <th>User_id</th>
                <th>Username</th>
                <th>User_first_name</th>
                <th>User_last_name</th>
                <th>Roles</th>
                <th>User_deleted</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.getId }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.userLastName }}</td>
                <td>{{ user.userFirstName }}</td>
                <td>
                {% for role in user.roles %}
                    {{ role }},
                {%  endfor %}
                </td>

                <td>{{ user.userDeleted ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('user_show', {'user_id': user.getId}) }}"><i class="fas fa-eye btn btn-secondary" style="color:">  </i></a>
                    <a href="{{ path('user_edit', {'user_id': user.getId}) }}"><i class="fas fa-pen btn btn-secondary"></i></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    
{% endblock %}

templates/user/new.html.twig
{% extends 'includes/base-template.html.twig' %}

{% block body %}

    <h1>Create new User</h1>
    

    {{ include('user/_form.html.twig') }}
    <br>
    <div class="text-center">
    	<a class="btn btn-secondary" href="{{ path('user_index') }}">back to list</a>
    </div>
{% endblock %}

templates/user/show.html.twig
{% extends 'includes/base-template.html.twig' %}

{% block body %}
<div class="body userdetails">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <span class="navbar-brand" href="#">Fiche utilisateur</span>
    </nav>
    <div class="ml-2 doc-infos" align="center">
        <p><b>Utilisateur :</b> {{ user.username }}<br/>
            <b>First name :</b> {{ user.userFirstName}}<br/>
            <b>Last name :</b> {{ user.userLastName }}<br/>
            <b>Role :</b> {% for role in user.roles %}
                        {{ role }},
            {%  endfor %}<br/>
    </div>
</div>
{% endblock %}